"project_id_env": "CROWDIN_PROJECT_ID"                     #open project settings and go to API section
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

"files": [
  {
    "source": "/libgambatte/libretro/intl/_us/*.json",                                      #source files filter
    "translation": "/libgambatte/libretro/intl/_%two_letters_code%/%original_file_name%",   #where translations are stored
    "skip_untranslated_strings": true
  },
]
