# Upload sources to Crowdin for translation & convert new translations

name: Crowdin Workflow

on:
  push:
    branches: [ master ]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        
      - name: Crowdin Pre
        shell: bash
        run: |
          cd ./libgambatte/libretro
          python3 crowdin_pre.py "gambatte-libretro"

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: crowdin action
        uses: crowdin/github-action@1.0.4
        with:
          upload_sources: true
          download_translations: true
        env:
          CROWDIN_PROJECT_ID: "470308"
          CROWDIN_PERSONAL_TOKEN: "92c1588f8fc5b24f1e70e85cabd9b8fe5b22dbe9aec7a9d885e5a5b3d8d673df52352a52c80db0ef"
          
      - name: Crowdin Post
        shell: bash
        run: |
          cd ./libgambatte/libretro
          python3 crowdin_post.py "gambatte-libretro"
