# Upload sources to Crowdin for translation & convert new translations

name: Crowdin Workflow

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        
      - name: Crowdin Pre
        shell: bash
        run: |
          cd ../gambatte-libretro/libgambatte/libretro/
          python3 crowdin_pre.py "gambatte-libretro"

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: crowdin action
        uses: crowdin/github-action@1.0.4
        with:
          upload_sources: true
          download_translations: true
        env:
          CROWDIN_PROJECT_ID: "470308"
          CROWDIN_PERSONAL_TOKEN: ""
          
      - name: Crowdin Post
        shell: bash
        run: |
          cd ../gambatte-libretro/libgambatte/libretro/
          python3 crowdin_post.py "gambatte-libretro"
